cc_library(
    name = "brain",
    srcs = ["brain.cc"],
    hdrs = ["brain.h"],
    deps = [],
)

cc_test(
    name = "brain_test",
    srcs = ["brain_test.cc"],
    deps = [
        ":brain",
        "@com_google_googletest//:gtest_main",
    ],
)
